### ISSUE TITLE
indeterminate mode?

### ISSUE THREAD

**Issue by robertoestivill** [lopspower/CircularProgressBar#1]
Any plans to support indeterminate mode ? or offset ?
It looks quite simple to implement, would you take a pull request for this functionality ?
Thanks

**Comment by lopspower** [comment]
Thanks for your feedback.
Indeed, an indeterminate mode can be interesting.
Nevertheless, the pull to refresh has no place in this project that isn't the main subject.

**Comment by robertoestivill** [comment]
I think you might have miss read. I was actually asking you if you would take a pull request for the indeterminate functionality as I was thinking about implementing this myself.

**Comment by lopspower** [comment]
Oh sorry, I'm french and I don't a have a good english. Of course I accept any help !!

**Comment by HamletLeon** [comment]
Well. I suggest to make a method to change the startangle.  I need to change that variable but it's block (I'm a beginner). ._.

**Comment by brspurri** [comment]
I'd love to see this as well. +1

**Comment by lopspower** [comment]
Now available in new version:
```groovy
implementation 'com.mikhaellopez:circularprogressbar:2.0.0'
```
