### ISSUE TITLE
some android roms setProgressWithAnimation not work

### ISSUE THREAD

**Issue by lindow2009** [lopspower/CircularProgressBar#13]
maybe ObjectAnimator automatically set the progress not work,so should add a update Listener?

**Comment by lopspower** [comment]
Fix in [https://github.com/lopspower/CircularProgressBar/commit/c1193c6e5cd4bd684562082a2e25e16d7eb963dd](https://github.com/lopspower/CircularProgressBar/commit/c1193c6e5cd4bd684562082a2e25e16d7eb963dd)
