### ISSUE TITLE
Cancel Progress Animation

### ISSUE THREAD

**Issue by dvrbear** [lopspower/CircularProgressBar#15]
```
public class CircularProgressBarExtended extends CircularProgressBar {

	private ObjectAnimator objectAnimator;
	public CircularProgressBarExtended(Context context, AttributeSet attrs) {
		super(context, attrs);
	}

	public void setProgressWithAnimation(float progress, int duration, TimeInterpolator interpolator) {
		objectAnimator = ObjectAnimator.ofFloat(this, "progress", progress);
		objectAnimator.setDuration(duration);
		objectAnimator.setInterpolator(interpolator);
		objectAnimator.start();
	}

	public void cancelAnimation(){
		if(objectAnimator != null){
			objectAnimator.cancel();
		}
	}

}
```

**Comment by Marcostar** [comment]
Resolved yet? I want pause and resume functionality but I am unable to do that with this

**Comment by Marcostar** [comment]
Even clearAnimation() is also not working. Is there a method to stop showing animation?

**Comment by lopspower** [comment]
Animation is clear when view is DetachedFromWindow & when you call setProgress manually.
Available in this commit [https://github.com/lopspower/CircularProgressBar/commit/e9ca4879a79b631706a5f61e43917299b35bae5b](https://github.com/lopspower/CircularProgressBar/commit/e9ca4879a79b631706a5f61e43917299b35bae5b)

**Comment by bryan-ibrahim** [comment]
I used `.setProgressWithAnimation(0);` to reversethe animation back to the start
