### ISSUE TITLE
Beware or Proguard Incompatibilities

### ISSUE THREAD

**Issue by AllanWang** [lopspower/CircularProgressBar#17]
[ObjectAnimator](https://github.com/lopspower/CircularProgressBar/blob/master/circularprogressbar/src/main/java/com/mikhaellopez/circularprogressbar/CircularProgressBar.java#L166) uses reflection to call its method, which won't work if a user proguards their application. Either ignore this class for proguard, or check if ValueAnimator can be used. Example:

```java
ValueAnimator animator = ValueAnimator.ofFloat(currentAngle, newAngle);
animator.setDuration(duration);
animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
	@Override
	public void onAnimationUpdate(ValueAnimator animation) {
		...
		invalidate();
	}
});
animator.start();
```

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularProgressBar/commit/94144be2d179691086c8f72b9f26b16b6a662976](https://github.com/lopspower/CircularProgressBar/commit/94144be2d179691086c8f72b9f26b16b6a662976)
