### ISSUE TITLE
Get Progress State

### ISSUE THREAD

**Issue by HosseinKurd** [lopspower/CircularProgressBar#22]
How i can get Progress State ?

i used :
`        CircularProgressBar circularProgressBar = view.findViewById(R.id.cpg_verify_code_fragment);`
`        circularProgressBar.setProgressWithAnimation(100, 120000);`

I need to know how many steps passed And how many reminds, progress And duration ?

**Comment by lopspower** [comment]
Now you can used a progressChangedListener:
```java
circularProgressBar.setOnProgressChangedListener(new CircularProgressBar.CircularProgressChangeListener() {
    @Override
    public void onProgressChanged(float progress) {
        //...
    }
});
```
