### ISSUE TITLE
Why just support float number?

### ISSUE THREAD

**Issue by reza-khalafi** [lopspower/CircularProgressBar#30]
Hello. 
In this code:  

```
progressBar.setOnProgressChangedListener(new CircularProgressBar.ProgressChangeListener() {
            @Override
            public void onProgressChanged(float progress) {
            }
        });
```

> **float progress**

I need to work with Double number but your library just support float progress number. 
Is there any way to fix it?

**Comment by lopspower** [comment]
The only difference between Double and Float is the number of bytes allocated (the size of your number). To manage a progressBar I think that Float is enough (not accurate enough visually to see the difference on big value). For info by default it's an Int that must be set for [the native Android ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar.html#setProgress(int)).

In your case it is enough just to have your max value and to calculate the ratio of your progress on 100.
