### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by roknimohsen** [lopspower/CircularProgressBar#31]
This library is in version 3.0.2
Why don't you create a Release?

**Comment by lopspower** [comment]
You want a release note ? It's a small library so you can see the change but I can create a release version with note if you want ?

**Comment by roknimohsen** [comment]
It's more than just the note. It shows the project improvement over time and how alive it is.
It also helps the developers see what has been done so far and in what way they can contribute to make it better, if it is your intent I mean.

**Comment by lopspower** [comment]
Ok, I understand.  Yes it is an open source project so I am very open to contributions for its improvement. Monday I will create a Release.

**Comment by lopspower** [comment]
The 3.0.2 is now available with release note here:
https://github.com/lopspower/CircularProgressBar/releases/tag/3.0.2
