### ISSUE TITLE
How to display a gradient progress bar？

### ISSUE THREAD

**Issue by aojiaoqiang** [lopspower/CircularProgressBar#33]
Thanks to your open source, I now want to set ‘’cpb_progressbar_color‘’ to a gradient color effect. To make it look cooler, how do I do it?

**Comment by lopspower** [comment]
The following properties must be used:
`cpb_progressbar_color_start` and `cpb_progressbar_color_end` instead of `cpb_progressbar_color`

You can also use `cpb_progressbar_color_direction` to change the direction.

Please watching the readme everything is written.
