### ISSUE TITLE
Initialize CircularProgressBar with no AttributeSet

### ISSUE THREAD

**Issue by oshetima** [lopspower/CircularProgressBar#34]
Hello,
I define the CircularProgressBar in the Kotlin class and not in the xml file. In the previous versions I was able to initialize it passing null as attributeSet while with the new version I can't. Can you please make it possible to initialize it with a null attributeSet parameter again? 
Many thanks for your time.

**Comment by lopspower** [comment]
Fix on the last version:

```groovy
implementation 'com.mikhaellopez:circularprogressbar:3.0.3'
```

**Comment by oshetima** [comment]
Thanks man!
