### ISSUE TITLE
Restart animation

### ISSUE THREAD

**Issue by eldarovich99** [lopspower/CircularProgressBar#35]
How to restart animation? 
setProgressWithAnimation(float progress) just do nothing.
I need it for progressbar for recyclerview because I don't want recreate progressbar just to show animation.

**Comment by lopspower** [comment]
You can play with the value of the progress. If you want to restart animation from 0 to 50 for example. You can set the progress to 0 without animation and used setProgressWithAnimation to 50.

**Comment by eldarovich99** [comment]
> You can play with the value of the progress. If you want to restart animation from 0 to 50 for example. You can set the progress to 0 without animation and used setProgressWithAnimation to 50.

Thanks, it works. Can I launch animation with indeterminate mode?

**Comment by lopspower** [comment]
I'm not sure to understand your question. "indeterminate mode" it's an animation.
Play with the sample to see all the action you can do.
