### ISSUE TITLE
Add possibility to change DEFAULT_ANIMATION_DURATION

### ISSUE THREAD

**Issue by Kolyall** [lopspower/CircularProgressBar#36]
Add possibility to change DEFAULT_ANIMATION_DURATION, because I want to create indeterminate ProgressBar, but in result "loading" process looks like it is slow

**Comment by Kolyall** [comment]
I want to increase speed

**Comment by lopspower** [comment]
You can change the duration of your animation with `setProgressWithAnimation`:

```kotlin
val duration = 1000 // 1s
circularProgressBar.setProgressWithAnimation(65f, duration)
```

> because I want to create indeterminate ProgressBar

The indeterminate mode already exists: `circularProgressBar.indeterminateMode = true`
