### ISSUE TITLE
exclude dependency from lib org.jetbrains.kotlin:kotlin-stdlib:1.3.50

### ISSUE THREAD

**Issue by Kolyall** [lopspower/CircularProgressBar#38]
When I make:
`./gradlew -q app:dependencies`
Your lib has kotlin dependency 
```
+--- com.mikhaellopez:circularprogressbar:3.0.3
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.60 (*)
```
But lib rxanimation doesn't
```
+--- com.mikhaellopez:rxanimation:0.0.7
```

**Comment by lopspower** [comment]
I added this dependency so that users on **JAVA** can use this library.
Otherwise they will have an unclear error because they miss `kotlin-stdlib`.
For users under Kotlin this dependency will automatically override.
