### ISSUE TITLE
Progress not getting rendered in Android version 8.1.0 (Redmi & Moto G4 plus) phones

### ISSUE THREAD

**Issue by prdpcrank** [lopspower/CircularProgressBar#40]
It works fine with android pie but when tested on lower devices it fails to render

**Comment by lopspower** [comment]
Hello, the min version supported is API 14.
It's indicated on the README with this badge:
[![API](https://img.shields.io/badge/API-14%2B-brightgreen.svg?style=flat)](https://android-arsenal.com/api?level=14)
