### ISSUE TITLE
Move away from jcenter since it'll be shutdown on May 1st 2021

### ISSUE THREAD

**Issue by YuanLiou** [lopspower/CircularProgressBar#57]
Hi!

According to JFrog, jcenter will set sunset on May 1, 2021.

Here is the [announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

**Comment by lopspower** [comment]
CircularProgressBar is always available on maven. So in theory it's not a problem.
[https://dl.bintray.com/lopspower/maven/com/mikhaellopez/circularprogressbar/](https://dl.bintray.com/lopspower/maven/com/mikhaellopez/circularprogressbar/)

**Comment by YuanLiou** [comment]
Hi @lopspower  sorry to "at" you, This bintray URL is now responding 401 Forbidden now

Gradle can't get this library by added `maven(url = "https://dl.bintray.com/lopspower/maven")` in `build.gradle`.

**Comment by lopspower** [comment]
Hello, you are right.  A new dependency must be created on mavenCentral before February 2022. The current version remains accessible on jCenter.

**Comment by lopspower** [comment]
Sorry for the delay 🙏
The version 4.3.0 is now available on MavenCentral :
```groovy
implementation 'com.mikhaellopez:circularimageview:4.3.0'
```
