### ISSUE TITLE
Move out the library from Jcenter

### ISSUE THREAD

**Issue by edgar-zigis** [lopspower/CircularProgressBar#58]
Hello, Jcenter is bound to shut down soon. Please place your library on MavenCentral for it to be used :)

**Comment by fabredthunder** [comment]
+1 Same issue here. 
Would be nice to put it on MavenCentral ! :)

**Comment by fvermeulen** [comment]
@lopspower yeah would be nice

**Comment by elhm** [comment]
very nice ;)

**Comment by jjoseba** [comment]
This would be awesome to be able to keep using the library in the future!

**Comment by lopspower** [comment]
Sorry for the delay 🙏
The version 3.1.0 is now available on MavenCentral :
```groovy
implementation 'com.mikhaellopez:circularprogressbar:3.1.0'
```
