### ISSUE TITLE
does not work in Relative Layout :(

### ISSUE THREAD

**Issue by 123vipulj** [lopspower/CircularProgressBar#7]
when i set the root layout to relative layout  progress bar goes off itself when app started  .

**Comment by lopspower** [comment]
The library works very well in a RelativeLayout. I don't understand your problem.

ex with progress text in center:

    <RelativeLayout
        android:layout_width="90dp"
        android:layout_height="90dp">

        <com.mikhaellopez.circularprogressbar.CircularProgressBar
            android:id="@+id/progressbar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:cpb_background_progressbar_color="@color/pink_light"
            app:cpb_background_progressbar_width="4dp"
            app:cpb_progressbar_color="@color/pink"
            app:cpb_progressbar_width="4dp"/>

        <TextView
            android:id="@+id/text_progressbar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:text="0"
            android:textColor="@color/pink"
            android:textSize="30sp"/>

    </RelativeLayout>

**Comment by 123vipulj** [comment]
it worked
